data:
  train_img_dir: ./downloads/merged_all/valid/images
  train_label_dir: ./downloads/merged_all/valid/labels
  val_img_dir: ./downloads/merged_all/valid/images
  val_label_dir: ./downloads/merged_all/valid/labels
  test_img_dir: ./downloads/merged_all/test/images
  test_label_dir: ./downloads/merged_all/test/labels
model:
  num_classes: 56